### ISSUE TITLE
The logo text is not visible clearly.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Lucy-Store-Design#14]
**Actual result:**
The logo text is not visible clearly.
![image](https://user-images.githubusercontent.com/102131636/187658438-a30a7d05-caf8-496f-afce-973455f08886.png)
**Expected result:**
The text of the logo should be visible clearly.

**Comment by ui-manjeshyadav** [comment]
@sudhanshu0603 Brother, the client has given this logo, so what can I do?

**Comment by sudhanshu0603** [comment]
ok ok
