### ISSUE TITLE
The navigation images are not clickable.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Lucy-Store-Design#18]
**Actual result:**
The navigation images are not clickable.
![image](https://user-images.githubusercontent.com/102131636/187661637-7e15307b-754b-4a7e-a7ad-5e98973ac119.png)
![image](https://user-images.githubusercontent.com/102131636/187661661-e49fb6ff-bc3b-4d7b-9ea2-4dce95159d57.png)
![image](https://user-images.githubusercontent.com/102131636/187661690-862e6050-6fb9-4e21-8d18-9b0a6aa0ac00.png)
![image](https://user-images.githubusercontent.com/102131636/187661710-6c36ad94-e516-4026-80c8-4ab9897ca802.png)

**Expected result:**
The images of the header navigation should be clicking and should open the page related to it.

**Comment by sudhanshu0603** [comment]
![image](https://user-images.githubusercontent.com/102131636/188149407-a287c090-50bc-45d7-90fe-25b724c2d042.png)
@devAmeer-Hamza , when we hover on women navigation and select the blue image then the children's accessories collection page is opening, pls check the linking of the image.

**Comment by devAmeer-Hamza** [comment]
as I have not any update regarding image linking so as of now its a demo link

**Comment by sudhanshu0603** [comment]
ok
