### ISSUE TITLE
The home page banners are looking blurry.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Lucy-Store-Design#19]
**Actual result:**
The home page banners are looking blurry, and text is looking very light blurry.
![image](https://user-images.githubusercontent.com/102131636/187662637-3ff5e5d7-b55e-4deb-b5d7-0e4ffb7f9bf3.png)
![image](https://user-images.githubusercontent.com/102131636/187663023-c3aea72a-0cee-4453-a13c-0d72b94ca915.png)

**Expected result:**
The banners should not be blurry.

**Comment by ui-manjeshyadav** [comment]
client images update @sudhanshu0603

**Comment by sudhanshu0603** [comment]
@ui-manjeshyadav , the updates banners are not of standard size. they are coming of in whole page, pls make it of standard size.
![image](https://user-images.githubusercontent.com/102131636/188149136-485a6df5-ad58-418e-8ebc-a27f10bf4d84.png)
![image](https://user-images.githubusercontent.com/102131636/188149177-0d799479-2546-4df3-ae46-c613382c5021.png)

**Comment by ui-manjeshyadav** [comment]
@sudhanshu0603 this is a standard size 1920x1000px kindly please check
