### ISSUE TITLE
In footer, the mobile number is not clickable.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Lucy-Store-Design#2]
**Actual result:**
In footer, the mobile number is not clickable.
![image](https://user-images.githubusercontent.com/102131636/187635540-a532037d-64cd-4c0d-a372-082d41e15f12.png)

**Expected result:**
The mobile number should be clickable.

**Comment by sudhanshu0603** [comment]
@devAmeer-Hamza , only some part of the phone number is clickable rest is not clickable.

**Comment by devAmeer-Hamza** [comment]
@sudhanshu0603  as I checked its default functionalist which is provided by  theme itself . kindly ignore it as it is work up to the mark

**Comment by sudhanshu0603** [comment]
ok
