### ISSUE TITLE
Client testimonial section, we can use the slider, empty space is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Lucy-Store-Design#43]
**Actual result:**
Client testimonial section, we can use the slider, empty space is coming.
![image](https://user-images.githubusercontent.com/102131636/187853828-821d01ae-cc8e-4643-bcdd-0129b4a517ab.png)

**Expected result:**
The empty space can be removed, we can use the slider.

**Comment by ui-manjeshyadav** [comment]
@devAmeer-Hamza please add slider in mobile view @sudhanshu0603 is not my fault please let ameer

**Comment by sudhanshu0603** [comment]
the text will overlappp behind the slider

**Comment by sudhanshu0603** [comment]
ok, resolved
