### ISSUE TITLE
In search page, input field when we type the digit then the border is  breaking.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Lucy-Store-Design#44]
**Actual result:**
In search page, input field when we type the digit then the border is  breaking.
![image](https://user-images.githubusercontent.com/102131636/187856808-2da26297-d24f-44a6-9e0e-1d7b4c0b1cba.png)

**Expected result:**
The border is breaking when we are typing the digits on the search input field.

**Comment by sudhanshu0603** [comment]
ok, resolved

**Comment by sudhanshu0603** [comment]
![image](https://user-images.githubusercontent.com/102131636/188135448-0060e8d4-3e62-48c3-a3d3-139e83b7114d.png)
when we are typing the alphabet then the border is breaking.
NOTE: 1st time when we come on search bar and click alphabet then the border is breaking and alphabet is not typing.

**Comment by ui-manjeshyadav** [comment]
@sudhanshu0603 Bro this point is not see in my device i check all devices but i can't find

**Comment by sudhanshu0603** [comment]
ok
