### ISSUE TITLE
In collection page, when we click on the out of stock and instock the white border is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Lucy-Store-Design#45]
**Actual result:**
In collection page, when we click on the out of stock and instock the white border is coming.
https://bellabrina-boutique.myshopify.com/collections/dresses?filter.v.availability=1&filter.v.availability=0&filter.v.availability=1&filter.v.price.gte=&filter.v.price.lte=
![image](https://user-images.githubusercontent.com/102131636/189082980-16836fbc-6338-4e52-9c1a-f3b77b270ca5.png)

**Expected result:**
The white background border should not come.

**Comment by ui-manjeshyadav** [comment]
@sudhanshu0603 this is not a issue

**Comment by sudhanshu0603** [comment]
ok
